name: CI Pipeline
on: #[push]  # Запуск при push в репозиторий
  workflow_dispatch:
    inputs:
      name:
        description: "Nik"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Клонирует ркпозиторий
      - name: Run a script
        run: echo "Hello, GitHub Actions!"
